# Generated by Django 6.0.3 on 2026-03-18 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('primary_material', models.CharField(max_length=100)),
                ('secondary_material', models.CharField(blank=True, max_length=100, null=True)),
                ('material_ratio', models.CharField(max_length=20)),
                ('button_count', models.IntegerField(default=0)),
                ('zipper_count', models.IntegerField(default=0)),
                ('purity_score', models.FloatField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('optimal_path', models.CharField(default='Chemical Recycling', max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
