# Generated by Django 6.0.3 on 2026-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalpassport',
            name='batch_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
